### PR TITLE
Two compiler warning fixes due to generics

### PR DESCRIPTION
**Pull request by ctron**
Unfortunately it is not possible to clean out all compiler warnings in this file without using `@SuppressWarnings`, but it is a start 😉

### CODE REVIEW

**Comment by tsegismont** [comment]
If you update this class you need to update the solutions folder as well

**Comment by ctron** [comment]
Maybe you could point me to the right file, as I can't see find the `vertx-workshop-common` module in the `solutions` folder structure. Or did I misunderstand that?

**Comment by tsegismont** [comment]
Oops, my bad. You're right. The solution folder only has code for the
projects to modify.

2017-07-18 16:06 GMT+02:00 Jens Reimann <notifications@github.com>:

**Comment by cescoffier** [comment]
Thanks !

**Pull request merged**
