### PR TITLE
improve the english in the documentation : preface

### PR DESCRIPTION
**Pull request by abdlquadri**
I am not an English Language expert but I think the language of the docs can be improved. Therefore I started.

### CODE REVIEW

**Comment by cescoffier** [comment]
Thanks !

**Comment by abdlquadri** [comment]
Hi Clement,

Thanks really for the workshop.

Do you prefer I send the pull-requests chapter by chapter or I send everything once I am done.

**Comment by cescoffier** [comment]
Hi,

First thanks for your PR. 

About one or several PRs, it's really up to you (so what do you prefer). I will merge them and republish the tutorial after every merge.

**Comment by abdlquadri** [comment]
Great!

Thanks!

**Pull request merged**
